### ISSUE TITLE
0.1.0 Launch Checklist

### ISSUE THREAD

**Issue by torch2424** [wasmerio/webassembly.sh#40]
# Checklist

* [x] Merge: https://github.com/wasmerio/webassembly.sh/pull/38
* [x] Publish Wasmer-js 0.2.0
* [x] Implement Drag and drop with 0.2.0
* [x] Implement Query Params with 0.2.0
* [x] Implement IndexedDB (If we can fit it in,  Haven't looked at how commands are stored in the cache yet )
* [x] Update article with all the changes
* [x] Create an Icon for the PWA / Decide PWA Color [Maybe use this tool](https://jgilfelt.github.io/AndroidAssetStudio/icons-launcher.html#foreground.space.trim=1&foreground.space.pad=0&foreColor=E8EAF6%2C0&crop=0&backgroundShape=square&backColor=3F51B5%2C100&effects=none&elevate=0), here is the tools license on generated output (Just add link int README) [License](https://creativecommons.org/licenses/by/3.0/)
* [x] Make a cool README
* [x] Add Gifs to the Article

# Notes

* Wasm FileSystem will be done post-launch, in a new Copy-Pasted branch from master
